name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cgomesv/miniblog:latest .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  security_scan:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: sast-scan
        uses: AppThreat/sast-scan-action@1.0.2
        with:
          type: "nodejs"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, security_scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - name: Push Docker image to registry
        run: docker push cgomesv/miniblog:latest
