name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cgomesv/miniblog:latest .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  security_scan:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: sast-scan
        uses: AppThreat/sast-scan-action@1.0.2
        with:
          type: "nodejs"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, security_scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            cgomesv/miniblog:v1
            cgomesv/miniblog:latest

      - name: Telegram Notifier
        uses: nikhilbadyal/telegram-forwarder@0.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Pull Request #${{ github.event.number }} foi aberto por ${{ github.actor }}.
            Você pode revisá-lo aqui: ${{ github.event.pull_request.html_url }}

      


        
