name: DEPLOY

on:
  push:
    branches: [main]

jobs:
  DEPLOY:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{  secrets.USER  }}
          password: ${{  secrets.PASSWD  }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: .
          push: true
          tags: |
            cgomesv/miniblog:v1
            cgomesv/miniblog:latest
      


      
